name: Metadata updater

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f doc/assets/workflows/requirements.txt ]; then pip install -r doc/assets/workflows/requirements.txt; fi

    - name: Update metadata
      env:
        gh_repo: ${{ github.event.repository.name }}
        gh_url: ${{ github.server_url }}/${{ github.repository }}
        gh_branch: ${{ github.head_ref || github.ref_name }}
        gh_description: ${{ github.event.repository.name }}
        gh_repository: ${{ github.repository }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 doc/assets/workflows/update_metadata.py
        python3 doc/assets/workflows/update_kitspace.py

    - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Update metadata files
        commit_options: '-a'
